sonar.projectKey=ffdd_cardano-go-syn_88799bc1-13e1-4d0e-a8ad-0b6cc2428baa
sonar.projectName=cardano-go-syn
sonar.exclusions=**/*_test.go,blockfrost/**,cardano-cli/**,cli/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=
sonar.go.coverage.reportPaths=coverage.out
