sonar.projectKey=ffdd_cardano-go_8c93cce7-7644-448d-9616-15037ed6ff28
sonar.projectName=cardano-go
sonar.exclusions=**/*_test.go,blockfrost/**,cardano-cli/**,cli/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=
sonar.go.coverage.reportPaths=coverage.out
